"""Add delivery

Revision ID: 564605d87baf
Revises: 
Create Date: 2024-04-24 07:06:19.470918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564605d87baf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ACTIVATED', 'DONE', 'CANCELED', name='appointmentstatuses'), nullable=False),
    sa.Column('trainer_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    # ### end Alembic commands ###